#!/bin/bash
. /lib/lsb/init-functions
log_daemon_msg "Testing Plex Media Server"
(exec docker-start) >/dev/null 2>&1 & plid=$!
trap "kill $plid" EXIT SIGINT SIGTERM
log_progress_msg "."
timeout 1m bash -c \
  'trap "kill 0" SIGINT; . /lib/lsb/init-functions ; \
    until curl -s http://localhost:32400/web; do echo -n "." ; sleep 1; done'
rc=$?
if [ $rc -eq 0 ]; then
  log_success_msg
else
  log_failure_msg
fi
exit $rc
