#!/bin/bash
set -eo pipefail

echo "**** Starting Plex Media Server (https://plex.tv/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

t2 /templates
exec $*
exit 0
